server:
  port: 8087

spring:
  profiles:
    active: production
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace
        legacy_limit_handler: true
        proc:
          param_null_passing: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.tigo.com.gt
    port: 25
    properties:
      mail:
        smtp:
          auth: false
---

spring:
  config:
    activate:
      on-profile: development
  datasource:
    application:
      jndi-name: jdbc/AccruedDS
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.trace: debug
    gt.com.tigo: debug
azure:
  application:
    id: 7698b4d8-ba1d-46f1-bd19-5f2fa2137dc7
    callback-url: http://localhost:3000
log4j:
  logger:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---

spring:
  config:
    activate:
      on-profile: development-alt
  datasource:
    application:
      jndi-name: jdbc/AccruedDS
logging:
  level:
    org.hibernate.SQL: debug
    gt.com.tigo: debug
azure:
  application:
    id: 6726cadc-5679-4331-a736-51deec194d5d
    callback-url: http://localhost:3100

---

spring:
  config:
    activate:
      on-profile: test-remote
  datasource:
    application:
      jndi-name: jdbc/AccruedDS
logging:
  level:
    org.hibernate.SQL: debug
    gt.com.tigo: debug
azure:
  application:
    id: 26838411-7e2e-4701-85ba-22b7d562a019
    callback-url: https://corporateappsdev.tigo.com.gt/accrued-automation/

---


spring:
  config:
    activate:
      on-profile: test-local
  datasource:
    application:
      jndi-name: jdbc/AccruedDS
logging:
  level:
    org.hibernate.SQL: debug
    gt.com.tigo: debug
azure:
  application:
    id: a60a4839-0491-4dc5-a27c-0bf460156e10
    callback-url: http://localhost:7001/accrued-automation

---

spring:
  config:
    activate:
      on-profile: qa
  datasource:
    application:
      jndi-name: jdbc/AccruedDS
logging:
  level:
    org.hibernate.SQL: info
    gt.com.tigo: debug
azure:
  application:
    id: e1228f21-0fa8-4b38-9c1b-39153ca33512
    callback-url: https://corporateappsqa.tigo.com.gt/accrued-automation/

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    application:
      jndi-name: jdbc/AccruedDS
logging:
  level:
    org.hibernate.SQL: info
    gt.com.tigo: info
azure:
  application:
    id: e1228f21-0fa8-4b38-9c1b-39153ca33512
    callback-url: https://corporateapps.tigo.com.gt/accrued-automation/
